version: '3'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  api:
    build: .
    command: gunicorn -b 0.0.0.0:8000 core.app:app --reload
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - .:/opt/app/
    depends_on:
      - redis
